
# source aliases & helper functions
source ~/_bin/dot-common/aliases.sh
source ~/_bin/dot-common/env-bash.sh
source ~/_bin/dot-common/help-functions.sh

# initialize z - https://github.com/rupa/z
source ~/_bin/dot-common/z.sh
