
# Path to your oh-my-zsh installation.
export ZSH=/Users/aware/.oh-my-zsh

# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="steeef"

# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
)

# source oh-my-zsh
source $ZSH/oh-my-zsh.sh

# source aliases & helper functions
source ~/_bin/dot-common/aliases.sh
source ~/_bin/dot-common/help-functions.sh
